vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
env_prefix = "dev"
instance_type = "t2.nano"
#public_key_location = "/c/Users/user/.ssh/id_rsa.pub"
availability_zone = "us-east-1"
